package com.github.tavet.challenges.leetcode;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RepeatedSubstringPatternTest {
    RepeatedSubstringPattern repeatedSubstringPattern;

    @BeforeEach
    void setUp() {
        repeatedSubstringPattern = new RepeatedSubstringPattern();
    }

    @Test
    void testCase1() {
        final String test = "aba";

        final Boolean expected = false;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }


    @Test
    void testCase2() {
        final String test = "abcabcabcabc";

        final Boolean expected = true;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }
    @Test
    void testCase3() {
        final String test = "abab";

        final Boolean expected = true;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }

    @Test
    void testCase4() {
        final String test = "abac";

        final Boolean expected = false;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }

    @Test
    void testCase5() {
        final String test = "z";

        final Boolean expected = false;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }

    // Performance can be improved
    @Test
    void testCase6() {
        final String test = "zodwlwuxknpezmxxeksvyymlqyheptepjilxeiurxlvzasweerbcpnphnzmdssueahbhpvynivmiqioubqzqfqavpmaieumhbpqrkqgulsdbcryejzwrpwofioppkbylsoecekwrebvhvtleshxheloobdflgdxyrdcvobnsckbxdoexybgcnvsoaychbbfveksulhpnrqlwfptdsahfxbwxbyefbmafwsahcpwthjqmajrtlaykcwidwoixcifadfjfwgafrquscllpmlaoiktgacgdmlfpsrwozxvqppirbthphjfrtyxtadypogegxdwwasmpjxjmsqbzbgquhopjtqykwfqtippkjdbsakfvciudplzybphwfggblzwvqnfzqitttaoxjkbaxcyarfxynfzygxvwkaxdjtyetobeyeewheyamxzzdaajyvikyfnjalnubqaaxfyglwgxuhxzizkiussuaidavswxjxziezopvwnrgmsqndyjvsexahyyauxltwvxvlnshcmpqefdjdmhyqeaaeyczvnstksovfhehvuzzzclfqsdjwdjbelczawtmojhtslcnfdpffakysphqssrwfvyhsttgcacvngkvkzarbmpvbymvsfuxbsgvlzdpbfmroxmyyopachvfhjaapuzsognzhqrlwdekaqkzebbiiwnsgnsxktpybcajsrwquacxsmwyqzgaxtsfimcsgrthvtsqmqiislfkzdipcqqajkfuximdbhmxcfpoxxzqieckilbkdtmpesjbcxgdfucjbrazpzpzdrlnepyiikzoeirghxkmsoytgyuxxjycdmqhbqrjasyhapnkpzyjowewuzttitwnfmxgcqqejqllhbvwaufoqkkljfgtbchgqensufzdxmrenmdogiexurkfyqzzviglovgicfobrffhtivatbxnsjvrbwqweyisvocxvsyozgvtostjuszmdufeqybwwlqubsrwnskoyghoycyuwzjzvoelohjnszhttyrgsbvqjefkjfefgnhbenmsuvfowojppayhdvypbfzkmfsstztzmhtiebwapfrefpmkkmzmtyyfgqzzrsadztlfuhfmoyqtoegaqfolgnqmfpnxjnckiopdxwpmvhhlmplevcqbrinwyavjpyuxolankrbfzlsnafrvhjyyslxsnubcuxailcyvwzcvmuknzdkhnjhfwgxmbaovyqgjtggpfimucwhbztkoeutbasndtdztwhepnkguuuowsxztrmivgdyiwnmrtnmpwsgjemfyiwwatvvmjdkphiafymyrbkgxemiianikjekfbfrllbaumczkozdpllopzwzzkhlvnvaocuzpxcjjekvvjymujblixkjjtuhgrjvwdwlbyvmfhiargmnspbaplmahihpatkywjjzjgmoqwqhcfwuuxxlllmstvhvoutnffmonafdwvmbalxxiwivhupdqzygvutabgoqitufriirtfqeczzjvronqnuljnlmvbcgxylohthcaygcziouzckprgccvporqrzprmdafldhllkktygucqluynwucnntemkxyoyfbbmomwyiwgczzovxdrrgeebkqliobitcjgqxeqhbxkcyaxvdqplxtmhmarcbzwekewkknrnmdpmfohlfyweujlgjfikggqtmpfxewkqccehsluxmrbgcpmnwwzcdsxrhcolbbdddhmvuhvgaymcpyrlxqqainrpsictjfyomklhtgnvhcxwaqkxhazrpthjdlcmraadnnmiuaebedzeujedlfudadmdprpgrrlgfypbaveeyfkurqxcwshyxwcmntugngnugevgzbkzgwuxnrcllljjhlxufudsasmgwjoxkywsuqqjkuuxfeinpgjucmocgckclybxyyqsqieccychckwssiouwfydhihvgjuejmzbudeybgigseylmohjtgodovyxgubphcrbfxcjfkpxqpkfdsqzaecobcliwpxdrqhznjksvzslqeqtyisymwnoaawxrvcjmjkzuuuptodjsvetezrsxgiyjevacxjojtnfpjxizatuxandzewynewwlrwnribcdqhtcgdbgzvgbijapfaemxazqymjiplohvhjdmlmnisotbqijrmxoowgokqxzdlgauseifqynkmgldqwwetmsrsjbkgcotjqpduzimxxwkekpuinbeztvtczekbufmkwphwzvvxshbewxolysmuqgypmlqgsfspuznuxitpqwvotjcueoquuolibbquijlfkybhiuyaqvrlftflhvfemqmntdjcouhauiideifuewflrnwzkdfwttmoyvsmqbpklxpphvjntrynewmoztnsmzjnwbbmdqzopogxlpkhglumhibhdobrpmelogatwzjmppldhvmpigcqqdzttakknrxdxxytyjhozstiqfxynzqfepyzskjhbjmygkuftdvuwqcovcmkbdpguphmztvdchditxppbmjzconxqbjteybbnjppclseuvoovedwsoxvekuwleqscrtsckhevbkswzgrflpxzmsgwncktscxmxpohytfzfxyefplqhlrtdxssacnuglgfcvmbqtcvsaaxsnnzyhueeoygsmbyzhdbcseslhqgjsdbftceazkgningwqevxkxccbwpkmvuebxmuaswzccomrujhbehlblpfhgpwejafhmbjexkibyvvteeuinhmyyrggiekserbtskzruivsfsnjwjtkqfkqysxhwjbdbcwvoxpkhmcmesxcbrouyzkzrjiqtjtwnptboilwwpkahiflbtfbupaobieutxsiollcuyaqoltxvaiwtnzqfaegkicghuovfazbyauonpmipwgkmfathgbsqdyxzmugmuknugbhxprmmxyacbtkhueazexaquifouuiavrxnilbhkbllwxusburfutyodfcyzmyufyhpjiwtlhghhbzkxsqrnqhrvlpuzpqenavxkrqwbzdkafuzxmtncaezmttnimuwmpvyhnukmauohooedhtfhxfvsaldmfbauwzdjvpwvlkccyjfhckrcpouszzeeahbwgeibwezhqdjrmoyrzrvqgpkfrpmrypoetwhpcgzumilaxmtydoqjgbrxsfoquewpcdfgmgbaomanyulcienohelzjcrdgntlsarggsgwfhkfbxjlbxakdnjnrcsypnjkpaqxvxuagghjfruhqwttkdibfdbxqmhipzfkybmejtppmkycgryswgwejzbcmkkblrnktzqeugtjsrlajlvhsrldqmfeyrhkjwuevmisscbmvongaioubzxtofyowhyfeujbhuvbwwotndapnqjorihfnhumrurvpdyyxuzvspofuqwhihvaqfffmbrfwlanoblnvmipeyxyrtgzbdztihyxiscgdfvtgggdvquzorxflffojghrnhqybvggaczikhnfxheozetmjaashjmuseuwzbczdejnlwvlebzffurrvtleexawevsdyxfbbqqonnztpayuvrnskzyoyymcvhitenwffnvscvnrvlosebmqakgzltdgclcgayngniyqfojdzxvgbkwdudchygqatsiusvagfaylohoqhjwivulqxqzvypxrhfnaaniiqgtenhwwsueopsgokfmivjbeppgreozwuudkbziuwnklhqzrxnbsxezovfhcujyqdbchdldzankhflaczdxyhwodbxhxgfomhqvkbyldnvkuimwjpvjzrxevvlsdqirzzmlcmwgztstcfsnwnxvhuzcrkwxdfocgdqkpmsrilkmsezosykzvjdmublzgabofrzugrlqeycwcdlwcvvxgalcczbkbfzgyaagrowwoauqefnickhjnunptpbuuaaucdbutxshymxeummwxvhmpvbjmefihgcjlddedxlbkkhgxtcwqmifjlqvrwfyehirnnvqlitxuadtvhpntzscmlzejecnokgdadvlloihqnbnusaosusgfsmoyrdodjrdmmozcyhulijgajwueodlipchgfxkrpnfdeficocowmwyxuvdiyptptcyyzipoxxubcceqguossosmlvwlmpbfrzgrjxhgubkyfqomkegcvyqgwmukcvqtwymhvwpqxzodpfrblxfiyvruklemiwhguwnqscipeyuvdnxrlezlcsfmdlylihtedgwvlenrdjmizlbmqdxuvegzpemznggrocobjdsmphwouaakdxeybmzssmuguazkcnoltizipywkywwdvdbypdqirkqnkpxpelcxwchlcdxabwfwzgwqlnaczqpmfpbmcdjyhrmjwllyhqwiztbkibphsevztwlwcxwlqivmuimdzjmaenmoqbvigrkbpxztuyfkgaxckjgjuulajyozzmkhfwlutkqoivarxxthjbtfveggcwgeislnowkhjaxtxykuxgdihwofdwnhsvldnzsdxclgekabimvgsbqcxejacwkxsvchuuluxyabicfrpazjbpnbwwdavnxplbwhwjbthewqgbhxeijhzwkvvqysdxhqzfyvrzqydmomqxjwhsfhrqcogcglapczwaunbkmhyctocemjzsqskvgsxmdxdhwzhqplcbsbfnrhrersyjkieqaeedbhlajusyhvbbwgopqitjarslbzdbdihgrugaqzayubzskqjcydlawflaerdjzkqsgwtzvtzrxaljqvlqawrybcyivcrwohpxgkwbdvvcvglobweduvcyaagvezsvjhsprqswlnbiwmwzlddfyfdahlwonqjwzdlstfogtrorgnqrqvyqacrkppacflyeolwhrmnmgddmsvdirbbtfufvjhzosauglspegesmkxyctbnmfofkinhrujhnjdvuvnbbrtozodwlwuxknpezmxxeksvyymlqyheptepjilxeiurxlvzasweerbcpnphnzmdssueahbhpvynivmiqioubqzqfqavpmaieumhbpqrkqgulsdbcryejzwrpwofioppkbylsoecekwrebvhvtleshxheloobdflgdxyrdcvobnsckbxdoexybgcnvsoaychbbfveksulhpnrqlwfptdsahfxbwxbyefbmafwsahcpwthjqmajrtlaykcwidwoixcifadfjfwgafrquscllpmlaoiktgacgdmlfpsrwozxvqppirbthphjfrtyxtadypogegxdwwasmpjxjmsqbzbgquhopjtqykwfqtippkjdbsakfvciudplzybphwfggblzwvqnfzqitttaoxjkbaxcyarfxynfzygxvwkaxdjtyetobeyeewheyamxzzdaajyvikyfnjalnubqaaxfyglwgxuhxzizkiussuaidavswxjxziezopvwnrgmsqndyjvsexahyyauxltwvxvlnshcmpqefdjdmhyqeaaeyczvnstksovfhehvuzzzclfqsdjwdjbelczawtmojhtslcnfdpffakysphqssrwfvyhsttgcacvngkvkzarbmpvbymvsfuxbsgvlzdpbfmroxmyyopachvfhjaapuzsognzhqrlwdekaqkzebbiiwnsgnsxktpybcajsrwquacxsmwyqzgaxtsfimcsgrthvtsqmqiislfkzdipcqqajkfuximdbhmxcfpoxxzqieckilbkdtmpesjbcxgdfucjbrazpzpzdrlnepyiikzoeirghxkmsoytgyuxxjycdmqhbqrjasyhapnkpzyjowewuzttitwnfmxgcqqejqllhbvwaufoqkkljfgtbchgqensufzdxmrenmdogiexurkfyqzzviglovgicfobrffhtivatbxnsjvrbwqweyisvocxvsyozgvtostjuszmdufeqybwwlqubsrwnskoyghoycyuwzjzvoelohjnszhttyrgsbvqjefkjfefgnhbenmsuvfowojppayhdvypbfzkmfsstztzmhtiebwapfrefpmkkmzmtyyfgqzzrsadztlfuhfmoyqtoegaqfolgnqmfpnxjnckiopdxwpmvhhlmplevcqbrinwyavjpyuxolankrbfzlsnafrvhjyyslxsnubcuxailcyvwzcvmuknzdkhnjhfwgxmbaovyqgjtggpfimucwhbztkoeutbasndtdztwhepnkguuuowsxztrmivgdyiwnmrtnmpwsgjemfyiwwatvvmjdkphiafymyrbkgxemiianikjekfbfrllbaumczkozdpllopzwzzkhlvnvaocuzpxcjjekvvjymujblixkjjtuhgrjvwdwlbyvmfhiargmnspbaplmahihpatkywjjzjgmoqwqhcfwuuxxlllmstvhvoutnffmonafdwvmbalxxiwivhupdqzygvutabgoqitufriirtfqeczzjvronqnuljnlmvbcgxylohthcaygcziouzckprgccvporqrzprmdafldhllkktygucqluynwucnntemkxyoyfbbmomwyiwgczzovxdrrgeebkqliobitcjgqxeqhbxkcyaxvdqplxtmhmarcbzwekewkknrnmdpmfohlfyweujlgjfikggqtmpfxewkqccehsluxmrbgcpmnwwzcdsxrhcolbbdddhmvuhvgaymcpyrlxqqainrpsictjfyomklhtgnvhcxwaqkxhazrpthjdlcmraadnnmiuaebedzeujedlfudadmdprpgrrlgfypbaveeyfkurqxcwshyxwcmntugngnugevgzbkzgwuxnrcllljjhlxufudsasmgwjoxkywsuqqjkuuxfeinpgjucmocgckclybxyyqsqieccychckwssiouwfydhihvgjuejmzbudeybgigseylmohjtgodovyxgubphcrbfxcjfkpxqpkfdsqzaecobcliwpxdrqhznjksvzslqeqtyisymwnoaawxrvcjmjkzuuuptodjsvetezrsxgiyjevacxjojtnfpjxizatuxandzewynewwlrwnribcdqhtcgdbgzvgbijapfaemxazqymjiplohvhjdmlmnisotbqijrmxoowgokqxzdlgauseifqynkmgldqwwetmsrsjbkgcotjqpduzimxxwkekpuinbeztvtczekbufmkwphwzvvxshbewxolysmuqgypmlqgsfspuznuxitpqwvotjcueoquuolibbquijlfkybhiuyaqvrlftflhvfemqmntdjcouhauiideifuewflrnwzkdfwttmoyvsmqbpklxpphvjntrynewmoztnsmzjnwbbmdqzopogxlpkhglumhibhdobrpmelogatwzjmppldhvmpigcqqdzttakknrxdxxytyjhozstiqfxynzqfepyzskjhbjmygkuftdvuwqcovcmkbdpguphmztvdchditxppbmjzconxqbjteybbnjppclseuvoovedwsoxvekuwleqscrtsckhevbkswzgrflpxzmsgwncktscxmxpohytfzfxyefplqhlrtdxssacnuglgfcvmbqtcvsaaxsnnzyhueeoygsmbyzhdbcseslhqgjsdbftceazkgningwqevxkxccbwpkmvuebxmuaswzccomrujhbehlblpfhgpwejafhmbjexkibyvvteeuinhmyyrggiekserbtskzruivsfsnjwjtkqfkqysxhwjbdbcwvoxpkhmcmesxcbrouyzkzrjiqtjtwnptboilwwpkahiflbtfbupaobieutxsiollcuyaqoltxvaiwtnzqfaegkicghuovfazbyauonpmipwgkmfathgbsqdyxzmugmuknugbhxprmmxyacbtkhueazexaquifouuiavrxnilbhkbllwxusburfutyodfcyzmyufyhpjiwtlhghhbzkxsqrnqhrvlpuzpqenavxkrqwbzdkafuzxmtncaezmttnimuwmpvyhnukmauohooedhtfhxfvsaldmfbauwzdjvpwvlkccyjfhckrcpouszzeeahbwgeibwezhqdjrmoyrzrvqgpkfrpmrypoetwhpcgzumilaxmtydoqjgbrxsfoquewpcdfgmgbaomanyulcienohelzjcrdgntlsarggsgwfhkfbxjlbxakdnjnrcsypnjkpaqxvxuagghjfruhqwttkdibfdbxqmhipzfkybmejtppmkycgryswgwejzbcmkkblrnktzqeugtjsrlajlvhsrldqmfeyrhkjwuevmisscbmvongaioubzxtofyowhyfeujbhuvbwwotndapnqjorihfnhumrurvpdyyxuzvspofuqwhihvaqfffmbrfwlanoblnvmipeyxyrtgzbdztihyxiscgdfvtgggdvquzorxflffojghrnhqybvggaczikhnfxheozetmjaashjmuseuwzbczdejnlwvlebzffurrvtleexawevsdyxfbbqqonnztpayuvrnskzyoyymcvhitenwffnvscvnrvlosebmqakgzltdgclcgayngniyqfojdzxvgbkwdudchygqatsiusvagfaylohoqhjwivulqxqzvypxrhfnaaniiqgtenhwwsueopsgokfmivjbeppgreozwuudkbziuwnklhqzrxnbsxezovfhcujyqdbchdldzankhflaczdxyhwodbxhxgfomhqvkbyldnvkuimwjpvjzrxevvlsdqirzzmlcmwgztstcfsnwnxvhuzcrkwxdfocgdqkpmsrilkmsezosykzvjdmublzgabofrzugrlqeycwcdlwcvvxgalcczbkbfzgyaagrowwoauqefnickhjnunptpbuuaaucdbutxshymxeummwxvhmpvbjmefihgcjlddedxlbkkhgxtcwqmifjlqvrwfyehirnnvqlitxuadtvhpntzscmlzejecnokgdadvlloihqnbnusaosusgfsmoyrdodjrdmmozcyhulijgajwueodlipchgfxkrpnfdeficocowmwyxuvdiyptptcyyzipoxxubcceqguossosmlvwlmpbfrzgrjxhgubkyfqomkegcvyqgwmukcvqtwymhvwpqxzodpfrblxfiyvruklemiwhguwnqscipeyuvdnxrlezlcsfmdlylihtedgwvlenrdjmizlbmqdxuvegzpemznggrocobjdsmphwouaakdxeybmzssmuguazkcnoltizipywkywwdvdbypdqirkqnkpxpelcxwchlcdxabwfwzgwqlnaczqpmfpbmcdjyhrmjwllyhqwiztbkibphsevztwlwcxwlqivmuimdzjmaenmoqbvigrkbpxztuyfkgaxckjgjuulajyozzmkhfwlutkqoivarxxthjbtfveggcwgeislnowkhjaxtxykuxgdihwofdwnhsvldnzsdxclgekabimvgsbqcxejacwkxsvchuuluxyabicfrpazjbpnbwwdavnxplbwhwjbthewqgbhxeijhzwkvvqysdxhqzfyvrzqydmomqxjwhsfhrqcogcglapczwaunbkmhyctocemjzsqskvgsxmdxdhwzhqplcbsbfnrhrersyjkieqaeedbhlajusyhvbbwgopqitjarslbzdbdihgrugaqzayubzskqjcydlawflaerdjzkqsgwtzvtzrxaljqvlqawrybcyivcrwohpxgkwbdvvcvglobweduvcyaagvezsvjhsprqswlnbiwmwzlddfyfdahlwonqjwzdlstfogtrorgnqrqvyqacrkppacflyeolwhrmnmgddmsvdirbbtfufvjhzosauglspegesmkxyctbnmfofkinhrujhnjdvuvnbbrto";
        final Boolean expected = true;

        assertEquals(expected, repeatedSubstringPattern.repeatedSubstringPattern(test));
    }
}
